// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sentry.OS.Persistence;

#nullable disable

namespace Sentry.OS.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sentry.OS.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("Applications", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b12880d-dc23-4f74-a28f-f71525390a9c"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The single web application used to sign in and administer Sentry.OS.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sentry Management Web App",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0],
                            Slug = "sentry-management-web-app"
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorDisplay")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredAtUtc");

                    b.ToTable("AuditLogs", "Audit");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Roles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full administrative access to the Sentry Management API.",
                            Level = 100,
                            Name = "GlobalAdministrator",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("RoleAssignments", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e07b9119-aaa4-4d10-9026-5968402243ce"),
                            AssignedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            RowVersion = new byte[0],
                            UserId = new Guid("e23b2eae-0a19-4e08-b752-282af674137a")
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.RoleScope", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("RoleScopes", "Auth");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("be5eadc2-d9e1-4bf1-93c0-0e29f2016f92")
                        },
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("42a42a3e-d8d1-42d2-894e-9151e69b0c2e")
                        },
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("b22ed850-e3ee-4831-8edb-9cb1b882a03c")
                        },
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("95bcf91b-28b0-494a-ac55-c0d9cd328298")
                        },
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("1c954386-ac5d-45cf-94ff-8595fdaccb76")
                        },
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("01ab320f-5bbc-4c68-a91d-e578b4501d75")
                        },
                        new
                        {
                            RoleId = new Guid("f76fd1c9-48d6-4381-81cf-290dc89caad7"),
                            ScopeId = new Guid("91710057-3024-42c6-8e53-f2a7958b9e00")
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AccessTokenLifetimeSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientSecretHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdentityTokenLifetimeSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RefreshTokenLifetimeSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("RefreshTokenRotationEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireClientSecret")
                        .HasColumnType("bit");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Clients", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            AccessTokenLifetimeSeconds = 3600,
                            ApplicationId = new Guid("0b12880d-dc23-4f74-a28f-f71525390a9c"),
                            ClientId = "sentry-management-web-app",
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sentry Management Web App (SPA)",
                            IdentityTokenLifetimeSeconds = 300,
                            IsActive = true,
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RefreshTokenLifetimeSeconds = 1209600,
                            RefreshTokenRotationEnabled = true,
                            RequireClientSecret = false,
                            RequirePkce = true,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientAllowedScope", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("ClientAllowedScopes", "Auth");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("be5eadc2-d9e1-4bf1-93c0-0e29f2016f92")
                        },
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("42a42a3e-d8d1-42d2-894e-9151e69b0c2e")
                        },
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("b22ed850-e3ee-4831-8edb-9cb1b882a03c")
                        },
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("95bcf91b-28b0-494a-ac55-c0d9cd328298")
                        },
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("1c954386-ac5d-45cf-94ff-8595fdaccb76")
                        },
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("01ab320f-5bbc-4c68-a91d-e578b4501d75")
                        },
                        new
                        {
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            ScopeId = new Guid("91710057-3024-42c6-8e53-f2a7958b9e00")
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientCorsOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Origin")
                        .IsUnique();

                    b.ToTable("ClientCorsOrigins", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("184172f9-0490-4bb0-906e-65a1bf1e9fb4"),
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            Origin = "http://localhost:5173"
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientGrantType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "GrantType")
                        .IsUnique();

                    b.ToTable("ClientGrantTypes", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09717d58-4a26-4945-9020-3f44d409bcc0"),
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            GrantType = "authorization_code"
                        },
                        new
                        {
                            Id = new Guid("3ef56dae-8cb1-465c-a011-7c66054fc362"),
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            GrantType = "refresh_token"
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientRedirectUri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Uri")
                        .IsUnique();

                    b.ToTable("ClientRedirectUris", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86d91a06-f0bc-4550-bff0-8538c99b538c"),
                            ClientId = new Guid("88a5a3f3-a5a8-4ed2-ad22-34181ff54a4f"),
                            Uri = "http://localhost:5173/callback"
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Acron",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Acron",
                            RowVersion = new byte[0],
                            Slug = "acron"
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomeOrganization")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrganizationAdministrator")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrganizationMemberships_HomeOrganization_PerUser")
                        .HasFilter("[IsHomeOrganization] = 1");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMemberships", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa1d0cb9-6f57-442d-bab0-7c43079cb7a8"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsHomeOrganization = true,
                            IsOrganizationAdministrator = true,
                            JoinedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0],
                            UserId = new Guid("e23b2eae-0a19-4e08-b752-282af674137a")
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Resources.ApiResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("ApiResources", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            ApplicationId = new Guid("0b12880d-dc23-4f74-a28f-f71525390a9c"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sentry Management API",
                            IsActive = true,
                            Name = "api-sentry-management",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Resources.Scope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ApiResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ApiResourceId", "Name")
                        .IsUnique();

                    b.ToTable("Scopes", "Auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be5eadc2-d9e1-4bf1-93c0-0e29f2016f92"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manage organizations",
                            Name = "organizations.manage",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("42a42a3e-d8d1-42d2-894e-9151e69b0c2e"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manage applications",
                            Name = "applications.manage",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("b22ed850-e3ee-4831-8edb-9cb1b882a03c"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manage API resources and scopes",
                            Name = "resources.manage",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("95bcf91b-28b0-494a-ac55-c0d9cd328298"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manage OAuth clients",
                            Name = "clients.manage",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("1c954386-ac5d-45cf-94ff-8595fdaccb76"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manage roles",
                            Name = "roles.manage",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("01ab320f-5bbc-4c68-a91d-e578b4501d75"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manage users and role assignments",
                            Name = "users.manage",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("91710057-3024-42c6-8e53-f2a7958b9e00"),
                            ApiResourceId = new Guid("d642f40e-bbef-4f01-b75c-f3ab939b240f"),
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Read the audit log",
                            Name = "audit.read",
                            OrganizationId = new Guid("02ab59f7-88da-4a57-b351-eea5207f34b8"),
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Tokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ClientId");

                    b.ToTable("RefreshTokens", "Auth");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlobalAdministrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("PhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TwoFactorMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e23b2eae-0a19-4e08-b752-282af674137a"),
                            AccessFailedCount = 0,
                            CreatedAtUtc = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "c_grimaldo@outlook.com",
                            EmailVerified = true,
                            FirstName = "Christian",
                            IsDeleted = false,
                            IsDisabled = false,
                            IsGlobalAdministrator = true,
                            LastName = "Grimaldo",
                            LockoutEnabled = true,
                            NormalizedEmail = "C_GRIMALDO@OUTLOOK.COM",
                            PasswordHash = "PBKDF2.SHA256.100000$vZ9+wS/g0hfSNvcAAizprg==$1AAjcmDjarHZQNAyaJ5vJF6v1wur5LJ0yb52HAeXFVs=",
                            PhoneNumberVerified = false,
                            RowVersion = new byte[0],
                            SecurityStamp = "SEEDSTAMP11062f87a73b41f6a26e6d580aeb02a9",
                            TwoFactorEnabled = false,
                            UserName = "c_grimaldo"
                        });
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClaimType", "ClaimValue")
                        .IsUnique();

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.UserProfilePicture", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserProfilePictures", "Identity");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Applications.Application", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", "Organization")
                        .WithMany("Applications")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.Role", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.RoleAssignment", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Authorization.Role", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Users.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.RoleScope", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Authorization.Role", "Role")
                        .WithMany("RoleScopes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Resources.Scope", "Scope")
                        .WithMany("RoleScopes")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.Client", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Applications.Application", "Application")
                        .WithMany("Clients")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientAllowedScope", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Clients.Client", "Client")
                        .WithMany("AllowedScopes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Resources.Scope", "Scope")
                        .WithMany("ClientAllowedScopes")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientCorsOrigin", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Clients.Client", "Client")
                        .WithMany("CorsOrigins")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientGrantType", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Clients.Client", "Client")
                        .WithMany("GrantTypes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.ClientRedirectUri", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Clients.Client", "Client")
                        .WithMany("RedirectUris")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Users.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Resources.ApiResource", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Applications.Application", "Application")
                        .WithMany("ApiResources")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Resources.Scope", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Resources.ApiResource", "ApiResource")
                        .WithMany("Scopes")
                        .HasForeignKey("ApiResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApiResource");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Tokens.RefreshToken", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Clients.Client", "Client")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sentry.OS.Domain.Tokens.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Sentry.OS.Domain.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.UserClaim", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Users.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.UserProfilePicture", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Users.User", "User")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("Sentry.OS.Domain.Users.UserProfilePicture", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.UserToken", b =>
                {
                    b.HasOne("Sentry.OS.Domain.Users.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Applications.Application", b =>
                {
                    b.Navigation("ApiResources");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Authorization.Role", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("RoleScopes");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Clients.Client", b =>
                {
                    b.Navigation("AllowedScopes");

                    b.Navigation("CorsOrigins");

                    b.Navigation("GrantTypes");

                    b.Navigation("RedirectUris");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Memberships");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Resources.ApiResource", b =>
                {
                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Resources.Scope", b =>
                {
                    b.Navigation("ClientAllowedScopes");

                    b.Navigation("RoleScopes");
                });

            modelBuilder.Entity("Sentry.OS.Domain.Users.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Memberships");

                    b.Navigation("ProfilePicture");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RoleAssignments");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
